### ISSUE TITLE
Şu amini siktigimin şeyini sil erax framework yap zucar adıni kullanma şikayet ederim seni

### ISSUE THREAD

**Issue by zukrein71** [emirhanbaltas34/zucar-framework#1]

**Comment by emirhanbaltas34** [comment]
Kudur satıcı orosbu çocuğu bi netflix için engelleyen bebe yarramı ye

**Comment by zukrein71** [comment]
GSYFJSJAJDNDJSJSİXİXİSJSJXJEJEJFHSHWHRHDUSİDİCSJHSFBBFBWHE

**Comment by zukrein71** [comment]
SEN HAYATIMDA GÖRDÜĞUM EN KALİTELİ OÇSUN AĞLA YARAGİMİNYE DİYOR BİDE DHDHSJJDJXDHSHHSBX

**Comment by zukrein71** [comment]
Velet sjjdjd

**Comment by zukrein71** [comment]
Velet sjjdjd

**Comment by emirhanbaltas34** [comment]
bruh

**Comment by WrenchDev** [comment]
emirhan istemiyor çocuk seni ayrıca ismin lisansını aldık erax framework yap.

**Comment by emirhanbaltas34** [comment]
kaliteli orosbu çocuğusunuz

**Comment by zukrein71** [comment]
Bize kaliteli orusbu çocugu diyen kişi 13 yaşında bir çocuk
lisansını aldım ismin kaldırmassan gg
